### ISSUE TITLE
seoalangcompiler -> seoa

### ISSUE THREAD

**Issue by ttakkku** [seoaapp/SeoaLangCompiler#1]
https://github.com/seoaapp/SeoaLangCompiler/blob/master/package.json#L2

**Comment by pmh-only** [comment]
it's compiler not runtime

**Comment by ttakkku** [comment]
ah

**Comment by pmh-only** [comment]
i will make another repo

**Comment by ttakkku** [comment]
http://github.com/seoaapp/Seoa ?

**Comment by pmh-only** [comment]
ah there is!

**Comment by ttakkku** [comment]
okay
